In [1]:
import numpy as np

import os

from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array

from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler

from PIL import Image, UnidentifiedImageError




model = ResNet50(weights='imagenet', include_top=False, input_shape=(255, 255, 3))



def extract_features(image_path):

  img = load_img(image_path, target_size=(255, 255))

  img_array = img_to_array(img)

  img_array = np.expand_dims(img_array, axis=0)

  img_array = preprocess_input(img_array)

   


  features = model.predict(img_array)

  return features.flatten()





folder_path = "C:/Users/Administrator/Desktop/testing"




image_paths = []

file_names = os.listdir(folder_path)



for file_name in file_names:

  if not file_name.startswith('.') and not file_name.endswith('.txt'):

    file_path = os.path.join(folder_path, file_name)

    try:

      img = Image.open(file_path)

      image_paths.append(file_path)

    except UnidentifiedImageError as e:

      print(f"Error processing image {file_path}: {e}")




X = np.array([extract_features(image_path) for image_path in image_paths])




print("Feature vectors:\n", X)




scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)






kmeans = KMeans(n_clusters=2, random_state=42)

labels = kmeans.fit_predict(X_scaled)




for i, label in enumerate(labels):

  print(f'Image {image_paths[i]} is in cluster {label}')



1/1 [==============================] - 0s 310ms/step
Feature vectors:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


c:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Image C:/Users/Administrator/Desktop/testing\santoshi_original.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original1.png is in cluster 1
Image C:/Users/Administrator/Desktop/testing\santoshi_original2.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original3.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original4.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original5.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original6.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original7.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original8.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\santoshi_original9.png is in cluster 0


In [2]:
print("hello")

hello
