In [1]:
import numpy as np

import os

from tensorflow.keras.applications import ResNet50, preprocess_input

from tensorflow.keras.preprocessing.image import load_img, img_to_array

from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler

from PIL import Image, UnidentifiedImageError



# Load the pre-trained ResNet50 model without the top layer (for feature extraction)

model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))



def extract_features(image_path):

  img = load_img(image_path, target_size=(224, 224))

  img_array = img_to_array(img)

  img_array = np.expand_dims(img_array, axis=0)

  img_array = preprocess_input(img_array)

   

  # Extract features using ResNet50

  features = model.predict(img_array)

  return features.flatten()



# Directory containing the images

folder_path = '"C:\Users\Administrator\Desktop\testing"'



# Get list of image file paths

image_paths = []

file_names = os.listdir(folder_path)



for file_name in file_names:

  if not file_name.startswith('.') and not file_name.endswith('.txt'):

    file_path = os.path.join(folder_path, file_name)

    try:

      img = Image.open(file_path)

      image_paths.append(file_path)

    except UnidentifiedImageError as e:

      print(f"Error processing image {file_path}: {e}")



# Extract features for each image

X = np.array([extract_features(image_path) for image_path in image_paths])



# Inspect the feature vectors

print("Feature vectors:\n", X)



# Normalize the features

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)





# Perform KMeans clustering

kmeans = KMeans(n_clusters=2, random_state=42)

labels = kmeans.fit_predict(X_scaled)



# Output the cluster labels for each image

for i, label in enumerate(labels):

  print(f'Image {image_paths[i]} is in cluster {label}')



SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: truncated \UXXXXXXXX escape (2905312039.py, line 45)

In [2]:
import numpy as np

import os

from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input


from tensorflow.keras.preprocessing.image import load_img, img_to_array

from sklearn.cluster import KMeans

from sklearn.preprocessing import StandardScaler

from PIL import Image, UnidentifiedImageError



# Load the pre-trained ResNet50 model without the top layer (for feature extraction)

model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))



def extract_features(image_path):

  img = load_img(image_path, target_size=(224, 224))

  img_array = img_to_array(img)

  img_array = np.expand_dims(img_array, axis=0)

  img_array = preprocess_input(img_array)

   

  # Extract features using ResNet50

  features = model.predict(img_array)

  return features.flatten()





In [3]:
folder_path = 'C:/Users/Administrator/Desktop/testing'



# Get list of image file paths

image_paths = []

file_names = os.listdir(folder_path)



for file_name in file_names:

  if not file_name.startswith('.') and not file_name.endswith('.txt'):

    file_path = os.path.join(folder_path, file_name)

    try:

      img = Image.open(file_path)

      image_paths.append(file_path)

    except UnidentifiedImageError as e:

      print(f"Error processing image {file_path}: {e}")



# Extract features for each image

X = np.array([extract_features(image_path) for image_path in image_paths])



# Inspect the feature vectors

print("Feature vectors:\n", X)



# Normalize the features

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)





# Perform KMeans clustering

kmeans = KMeans(n_clusters=2, random_state=42)

labels = kmeans.fit_predict(X_scaled)



# Output the cluster labels for each image

for i, label in enumerate(labels):

  print(f'Image {image_paths[i]} is in cluster {label}')


1/1 [==============================] - 0s 220ms/step
Feature vectors:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Image C:/Users/Administrator/Desktop/testing\viswa_original.png is in cluster 1
Image C:/Users/Administrator/Desktop/testing\viswa_original1.png is in cluster 1
Image C:/Users/Administrator/Desktop/testing\viswa_original2.png is in cluster 1
Image C:/Users/Administrator/Desktop/testing\viswa_original3.png is in cluster 0
Image C:/Users/Administrator/Desktop/testing\viswa_original4.png is in cluster 1
